[workspace]
resolver = "2"
members = [
	"crates/icy_draw", 
	"crates/icy_engine",
	"crates/icy_engine_gui",
	"crates/icy_play", 
	"crates/icy_sauce", 
	"crates/icy_sixel", 
	"crates/icy_term",
	"crates/icy_view",
	"crates/icy_view_gui",
]
[workspace.package]
version = "0.3.0"
edition = "2021"
authors = ["Mike Krüger <mkrueger@posteo.de>"]
license = "MIT or Apache-2.0"

[workspace.dependencies]
icy_engine = { path = "crates/icy_engine" }
icy_engine_gui = { path = "crates/icy_engine_gui" }
icy_sauce = { path = "crates/icy_sauce" }
icy_sixel = { path = "crates/icy_sixel" }
icy_view_gui = { path = "crates/icy_view_gui" }

zip = { version = "1.1.1"}
lazy_static = "1.4.0"
semver = "1.0.20"
thiserror = "1.0.57"
clap = { version = "4.5.4", features = ["derive"] }
log = "0.4.14"
chrono = { version = "0.4.37", features = ["serde"] }
serde = { version = "1.0.198", features = ["derive"] }
walkdir = "2.5.0"
i18n-embed = { version = "0.14.0", features = ["fluent-system", "desktop-requester"]} 
i18n-embed-fl = "0.8.0"
fluent-bundle = "0.15.2"
rust-embed = "8.3.0"
once_cell = "1.18.0"
toml = "0.8.12"
bstr = "1.9.1"
regex = "1.9.5"
directories = "5.0.1"
tokio = { version = "1.37.0", features = ["full"] }

egui = "0.27.2"
eframe = "0.27.2"
# eframe = { version = "0.27.2", default-features = false, features = [
#     "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
#     "default_fonts", # Embed the default egui fonts.
#     "glow",          # Use the glow rendering backend. Alternative: "wgpu".
#     "persistence",   # Enable restoring app state when restarting the app.
# ], optional = true }
egui_extras = { version="0.27.2", features = ["all_loaders", "svg", "image"] }
# egui_extras = { version="0.27.2", features = [] }
egui_glow = "0.27.2"
glow = "0.13.0"
egui-modal = "0.3.6"
egui-bind = "0.12.0"
egui_file = "0.17.0"
egui-notify = "0.14.0"

[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*
