name: Build
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [master]
    types: 
      - completed
env:
  CARGO_TERM_COLOR: always
jobs:
  build_windows:
    strategy:
      matrix:
        app: [icy_term, icy_draw, icy_view, icy_play]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare FILE_ID.DIZ
      run: |
        $VERSION=$(python tools\prep_diz.py ".\crates\${{ matrix.app }}\" "file_id.diz")
        echo "Version: $VERSION"
        
        Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$VERSION"
        get-content .\crates\${{ matrix.app }}\build\file_id.diz | %{$_ -replace "#VERSION","$VERSION"} >file_id.diz
    - name: Build exe
      run: |
        cd .\crates\${{ matrix.app }}
        cargo build --release
        cd ..\..
        move .\target\release\${{ matrix.app }}.exe .
    - name: 'Upload executable'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.app }}_${{ env.VERSION }}_windows
        path: |
          ${{ matrix.app }}.exe
          file_id.diz